# Generated by Django 6.0.7 on 2026-07-29 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TriggerTemplateMatrix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trigger', models.CharField(choices=[('login', 'Login'), ('logout', 'Logout'), ('inactive_1day', 'Not logged in for 1 day'), ('inactive_1week', 'Not logged in for 1 week')], max_length=50)),
                ('channel', models.CharField(choices=[('whatsapp', 'WhatsApp'), ('email', 'Email'), ('web_push', 'Web Push')], max_length=20)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('body', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'unique_together': {('trigger', 'channel')},
            },
        ),
    ]
